name: Code Checks

on:
  push:
    #branches:
    #  - main
  pull_request:

permissions:
  contents: read

jobs:
  quality-check:
    name: unit tests and phpstan L9
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
  
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
  
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
  
      - name: Run tests
        run: vendor/bin/phpunit tests --fail-on-warning --fail-on-risky
  
      - name: Run stan level 9
        run: vendor/bin/phpstan analyse -l 9 src
      
